# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ae4y4oZGHU7Z_eqADUci2MuU58Xdh9JQ
"""

x = [1,2,3]
for i in x:
  print(i/2)

import numpy as np
x=np.array([1,2,3])
print(x)

x/2

x*9

x+200

type(x)

#Random Function
import numpy as py
np.random.randint(0,10,4)

np.random.randint(0,10,(3,4))

np.random.randint(0,10,(2,3))

np.random.randint(100,200,10)

#Numpy Slicing
np.random.randint(0,10,(5,4))

#1d array
a=np.array([2,3,4])
print(a)

#2d array
b=np.array([[2,3,4],[8,9,10]])
print(b)

#3d array
c=np.array([[2,4,6],[8,10,12],[5,6,7]]),([[1,7,3],[5,5,6],[5,8,7]])
print(c)